### ISSUE TITLE
ERROR: Unable to run session Must specify at least one target to fetch or execute.

### ISSUE THREAD

**Issue by salamanders** [tzolov/mtcnn-java#5]
Error on small 300x300 png image:

```
import net.tzolov.cv.mtcnn.MtcnnService
import net.tzolov.cv.mtcnn.MtcnnUtil
import java.io.File
import javax.imageio.ImageIO

fun main() {
    val mtcnnService = MtcnnService()
    val inputImage = MtcnnUtil.to3ByteBGR(ImageIO.read(File("300.png")))
    val faceAnnotations = mtcnnService.faceDetection(inputImage)
    val annotatedImage = MtcnnUtil.drawFaceAnnotations(inputImage, faceAnnotations)
    ImageIO.write(annotatedImage, "png", File("./AnnotatedImage.png"))
}
```

```
2018-11-26 16:22:55.679019: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-11-26 16:22:55.679279: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 8. Tune using inter_op_parallelism_threads for best performance.
[main] INFO org.nd4j.linalg.factory.Nd4jBackend - Loaded [CpuBackend] backend
[main] INFO org.nd4j.nativeblas.NativeOpsHolder - Number of threads used for NativeOps: 4
[main] INFO org.nd4j.nativeblas.Nd4jBlas - Number of threads used for BLAS: 4
[main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Backend used: [CPU]; OS: [Mac OS X]
[main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Cores: [8]; Memory: [3.6GB];
[main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Blas vendor: [MKL]
Exception in thread "main" java.lang.IllegalStateException: ERROR: Unable to run session Must specify at least one target to fetch or execute.
	at org.nd4j.tensorflow.conversion.graphrunner.GraphRunner.run(GraphRunner.java:525)
	at net.tzolov.cv.mtcnn.MtcnnService.preparationStage(MtcnnService.java:286)
	at net.tzolov.cv.mtcnn.MtcnnService.rawFaceDetection(MtcnnService.java:235)
	at net.tzolov.cv.mtcnn.MtcnnService.faceDetection(MtcnnService.java:164)
	at net.tzolov.cv.mtcnn.MtcnnService.faceDetection(MtcnnService.java:133)
	at MainKt.main(Main.kt:14)
	at MainKt.main(Main.kt)

Process finished with exit code 1
```

**Comment by salamanders** [comment]
Same error on pivotal-ipo-nyse.jpg.  Using master-SNAPSHOT

**Comment by mhashem** [comment]
@salamanders what is your setup? OS + version, Java version?

**Comment by salamanders** [comment]
Java: 1.8.0_191
OS: Mac OS X, 10.14.1. x86_64

I uploaded a commit showing the error: https://github.com/salamanders/bestsmiles/tree/85153f1e0ae65c0f241c9cdbef348b3112ddcfb2

**Comment by Guppster** [comment]
I have the same issue. @salamanders did you get it working?

**Comment by salamanders** [comment]
Unfortunately I never did.
